# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgiMarvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgiMarvel
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper', '~> 3.4'
  pod 'SVProgressHUD'
  pod 'CryptoSwift'
  
  target 'AgiMarvelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AgiMarvelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
